
-- (C) 1992-2014 Altera Corporation. All rights reserved.                         
-- Your use of Altera Corporation's design tools, logic functions and other       
-- software and tools, and its AMPP partner logic functions, and any output       
-- files any of the foregoing (including device programming or simulation         
-- files), and any associated documentation or information are expressly subject  
-- to the terms and conditions of the Altera Program License Subscription         
-- Agreement, Altera MegaCore Function License Agreement, or other applicable     
-- license agreement, including, without limitation, that your use is for the     
-- sole purpose of programming logic devices manufactured by Altera and sold by   
-- Altera or its authorized distributors.  Please refer to the applicable         
-- agreement for further details.                                                 
    


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
USE ieee.std_logic_arith.all;

--***************************************************
--***                                             ***
--***   FLOATING POINT CORE LIBRARY               ***
--***                                             ***
--***   FP_LNLUTPOW.VHD                           ***
--***                                             ***
--***   Function: Look Up Table - LN()            ***
--***                                             ***
--***   Generated by MATLAB Utility               ***
--***                                             ***
--***   22/02/08 ML                               ***
--***                                             ***
--***   (c) 2008 Altera Corporation               ***
--***                                             ***
--***   Change History                            ***
--***                                             ***
--***                                             ***
--***                                             ***
--***                                             ***
--***                                             ***
--***************************************************

ENTITY fp_lnlutpow IS
PORT (
      add : IN STD_LOGIC_VECTOR (7 DOWNTO 1);
      logman : OUT STD_LOGIC_VECTOR (23 DOWNTO 1);
      logexp : OUT STD_LOGIC_VECTOR (8 DOWNTO 1)
     );
END fp_lnlutpow;

ARCHITECTURE rtl OF fp_lnlutpow IS

BEGIN

  pca: PROCESS (add)
  BEGIN
    CASE add IS
      WHEN "0000000" =>
            logman <= conv_std_logic_vector(0,23);
            logexp <= conv_std_logic_vector(0,8);
      WHEN "0000001" =>
            logman <= conv_std_logic_vector(3240472,23);
            logexp <= conv_std_logic_vector(126,8);
      WHEN "0000010" =>
            logman <= conv_std_logic_vector(3240472,23);
            logexp <= conv_std_logic_vector(127,8);
      WHEN "0000011" =>
            logman <= conv_std_logic_vector(333202,23);
            logexp <= conv_std_logic_vector(128,8);
      WHEN "0000100" =>
            logman <= conv_std_logic_vector(3240472,23);
            logexp <= conv_std_logic_vector(128,8);
      WHEN "0000101" =>
            logman <= conv_std_logic_vector(6147742,23);
            logexp <= conv_std_logic_vector(128,8);
      WHEN "0000110" =>
            logman <= conv_std_logic_vector(333202,23);
            logexp <= conv_std_logic_vector(129,8);
      WHEN "0000111" =>
            logman <= conv_std_logic_vector(1786837,23);
            logexp <= conv_std_logic_vector(129,8);
      WHEN "0001000" =>
            logman <= conv_std_logic_vector(3240472,23);
            logexp <= conv_std_logic_vector(129,8);
      WHEN "0001001" =>
            logman <= conv_std_logic_vector(4694107,23);
            logexp <= conv_std_logic_vector(129,8);
      WHEN "0001010" =>
            logman <= conv_std_logic_vector(6147742,23);
            logexp <= conv_std_logic_vector(129,8);
      WHEN "0001011" =>
            logman <= conv_std_logic_vector(7601377,23);
            logexp <= conv_std_logic_vector(129,8);
      WHEN "0001100" =>
            logman <= conv_std_logic_vector(333202,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0001101" =>
            logman <= conv_std_logic_vector(1060019,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0001110" =>
            logman <= conv_std_logic_vector(1786837,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0001111" =>
            logman <= conv_std_logic_vector(2513654,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010000" =>
            logman <= conv_std_logic_vector(3240472,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010001" =>
            logman <= conv_std_logic_vector(3967289,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010010" =>
            logman <= conv_std_logic_vector(4694107,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010011" =>
            logman <= conv_std_logic_vector(5420924,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010100" =>
            logman <= conv_std_logic_vector(6147742,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010101" =>
            logman <= conv_std_logic_vector(6874559,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010110" =>
            logman <= conv_std_logic_vector(7601377,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0010111" =>
            logman <= conv_std_logic_vector(8328194,23);
            logexp <= conv_std_logic_vector(130,8);
      WHEN "0011000" =>
            logman <= conv_std_logic_vector(333202,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0011001" =>
            logman <= conv_std_logic_vector(696611,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0011010" =>
            logman <= conv_std_logic_vector(1060019,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0011011" =>
            logman <= conv_std_logic_vector(1423428,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0011100" =>
            logman <= conv_std_logic_vector(1786837,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0011101" =>
            logman <= conv_std_logic_vector(2150246,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0011110" =>
            logman <= conv_std_logic_vector(2513654,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0011111" =>
            logman <= conv_std_logic_vector(2877063,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100000" =>
            logman <= conv_std_logic_vector(3240472,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100001" =>
            logman <= conv_std_logic_vector(3603881,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100010" =>
            logman <= conv_std_logic_vector(3967289,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100011" =>
            logman <= conv_std_logic_vector(4330698,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100100" =>
            logman <= conv_std_logic_vector(4694107,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100101" =>
            logman <= conv_std_logic_vector(5057516,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100110" =>
            logman <= conv_std_logic_vector(5420924,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0100111" =>
            logman <= conv_std_logic_vector(5784333,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101000" =>
            logman <= conv_std_logic_vector(6147742,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101001" =>
            logman <= conv_std_logic_vector(6511151,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101010" =>
            logman <= conv_std_logic_vector(6874559,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101011" =>
            logman <= conv_std_logic_vector(7237968,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101100" =>
            logman <= conv_std_logic_vector(7601377,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101101" =>
            logman <= conv_std_logic_vector(7964786,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101110" =>
            logman <= conv_std_logic_vector(8328194,23);
            logexp <= conv_std_logic_vector(131,8);
      WHEN "0101111" =>
            logman <= conv_std_logic_vector(151498,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110000" =>
            logman <= conv_std_logic_vector(333202,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110001" =>
            logman <= conv_std_logic_vector(514906,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110010" =>
            logman <= conv_std_logic_vector(696611,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110011" =>
            logman <= conv_std_logic_vector(878315,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110100" =>
            logman <= conv_std_logic_vector(1060019,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110101" =>
            logman <= conv_std_logic_vector(1241724,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110110" =>
            logman <= conv_std_logic_vector(1423428,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0110111" =>
            logman <= conv_std_logic_vector(1605133,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111000" =>
            logman <= conv_std_logic_vector(1786837,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111001" =>
            logman <= conv_std_logic_vector(1968541,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111010" =>
            logman <= conv_std_logic_vector(2150246,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111011" =>
            logman <= conv_std_logic_vector(2331950,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111100" =>
            logman <= conv_std_logic_vector(2513654,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111101" =>
            logman <= conv_std_logic_vector(2695359,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111110" =>
            logman <= conv_std_logic_vector(2877063,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "0111111" =>
            logman <= conv_std_logic_vector(3058768,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000000" =>
            logman <= conv_std_logic_vector(3240472,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000001" =>
            logman <= conv_std_logic_vector(3422176,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000010" =>
            logman <= conv_std_logic_vector(3603881,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000011" =>
            logman <= conv_std_logic_vector(3785585,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000100" =>
            logman <= conv_std_logic_vector(3967289,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000101" =>
            logman <= conv_std_logic_vector(4148994,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000110" =>
            logman <= conv_std_logic_vector(4330698,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1000111" =>
            logman <= conv_std_logic_vector(4512403,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001000" =>
            logman <= conv_std_logic_vector(4694107,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001001" =>
            logman <= conv_std_logic_vector(4875811,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001010" =>
            logman <= conv_std_logic_vector(5057516,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001011" =>
            logman <= conv_std_logic_vector(5239220,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001100" =>
            logman <= conv_std_logic_vector(5420924,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001101" =>
            logman <= conv_std_logic_vector(5602629,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001110" =>
            logman <= conv_std_logic_vector(5784333,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1001111" =>
            logman <= conv_std_logic_vector(5966038,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010000" =>
            logman <= conv_std_logic_vector(6147742,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010001" =>
            logman <= conv_std_logic_vector(6329446,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010010" =>
            logman <= conv_std_logic_vector(6511151,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010011" =>
            logman <= conv_std_logic_vector(6692855,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010100" =>
            logman <= conv_std_logic_vector(6874559,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010101" =>
            logman <= conv_std_logic_vector(7056264,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010110" =>
            logman <= conv_std_logic_vector(7237968,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1010111" =>
            logman <= conv_std_logic_vector(7419673,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1011000" =>
            logman <= conv_std_logic_vector(7601377,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1011001" =>
            logman <= conv_std_logic_vector(7783081,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1011010" =>
            logman <= conv_std_logic_vector(7964786,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1011011" =>
            logman <= conv_std_logic_vector(8146490,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1011100" =>
            logman <= conv_std_logic_vector(8328194,23);
            logexp <= conv_std_logic_vector(132,8);
      WHEN "1011101" =>
            logman <= conv_std_logic_vector(60645,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1011110" =>
            logman <= conv_std_logic_vector(151498,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1011111" =>
            logman <= conv_std_logic_vector(242350,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100000" =>
            logman <= conv_std_logic_vector(333202,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100001" =>
            logman <= conv_std_logic_vector(424054,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100010" =>
            logman <= conv_std_logic_vector(514906,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100011" =>
            logman <= conv_std_logic_vector(605759,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100100" =>
            logman <= conv_std_logic_vector(696611,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100101" =>
            logman <= conv_std_logic_vector(787463,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100110" =>
            logman <= conv_std_logic_vector(878315,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1100111" =>
            logman <= conv_std_logic_vector(969167,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101000" =>
            logman <= conv_std_logic_vector(1060019,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101001" =>
            logman <= conv_std_logic_vector(1150872,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101010" =>
            logman <= conv_std_logic_vector(1241724,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101011" =>
            logman <= conv_std_logic_vector(1332576,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101100" =>
            logman <= conv_std_logic_vector(1423428,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101101" =>
            logman <= conv_std_logic_vector(1514280,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101110" =>
            logman <= conv_std_logic_vector(1605133,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1101111" =>
            logman <= conv_std_logic_vector(1695985,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110000" =>
            logman <= conv_std_logic_vector(1786837,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110001" =>
            logman <= conv_std_logic_vector(1877689,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110010" =>
            logman <= conv_std_logic_vector(1968541,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110011" =>
            logman <= conv_std_logic_vector(2059394,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110100" =>
            logman <= conv_std_logic_vector(2150246,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110101" =>
            logman <= conv_std_logic_vector(2241098,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110110" =>
            logman <= conv_std_logic_vector(2331950,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1110111" =>
            logman <= conv_std_logic_vector(2422802,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111000" =>
            logman <= conv_std_logic_vector(2513654,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111001" =>
            logman <= conv_std_logic_vector(2604507,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111010" =>
            logman <= conv_std_logic_vector(2695359,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111011" =>
            logman <= conv_std_logic_vector(2786211,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111100" =>
            logman <= conv_std_logic_vector(2877063,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111101" =>
            logman <= conv_std_logic_vector(2967915,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111110" =>
            logman <= conv_std_logic_vector(3058768,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN "1111111" =>
            logman <= conv_std_logic_vector(3149620,23);
            logexp <= conv_std_logic_vector(133,8);
      WHEN others =>
           logman <= conv_std_logic_vector(0,23);
           logexp <= conv_std_logic_vector(0,8);
    END CASE;
  END PROCESS;

END rtl;
