# TCL File Generated by Component Editor 11.0
# Tue Jul 19 13:15:52 PDT 2011


# +-----------------------------------
# | 
# | no_reset 
# | Altera OpenCL 2011.07.19.13:15:52
# | 
# | 
# |    ./no_reset.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 10.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module no_reset
# | 
set_module_property DESCRIPTION "Permanently deassert reset"
set_module_property NAME no_reset
set_module_property VERSION 10.0
set_module_property GROUP "ACL Internal Components"
set_module_property AUTHOR "Altera OpenCL"
set_module_property DISPLAY_NAME "ACL No Reset"
set_module_property TOP_LEVEL_HDL_FILE no_reset.v
set_module_property TOP_LEVEL_HDL_MODULE no_reset
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file no_reset.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------


# +-----------------------------------
# | connection point no_reset
# | 
add_interface no_reset reset start
set_interface_property no_reset synchronousEdges NONE
set_interface_property no_reset ENABLED true
add_interface_port no_reset reset reset Output 1
# | 
# +-----------------------------------
