# (C) 1992-2014 Altera Corporation. All rights reserved.                         
# Your use of Altera Corporation's design tools, logic functions and other       
# software and tools, and its AMPP partner logic functions, and any output       
# files any of the foregoing (including device programming or simulation         
# files), and any associated documentation or information are expressly subject  
# to the terms and conditions of the Altera Program License Subscription         
# Agreement, Altera MegaCore Function License Agreement, or other applicable     
# license agreement, including, without limitation, that your use is for the     
# sole purpose of programming logic devices manufactured by Altera and sold by   
# Altera or its authorized distributors.  Please refer to the applicable         
# agreement for further details.                                                 
    


# TCL File Generated by Component Editor 11.0
# Wed Jun 08 10:53:55 PDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | acl_mem2x "Quad port memory" v1.0
# | Peter Yiannacouras 2011.06.08.10:53:55
# | 
# | 
# | /net/ttc-swnas1/home/pyiannac/OpenCL/memsystem/localmem/acl_mem2x.v
# | 
# |    ./acl_mem2x.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module acl_mem2x
# | 
set_module_property NAME acl_mem2x
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ACL
set_module_property AUTHOR "Peter Yiannacouras"
set_module_property DISPLAY_NAME "Quad port memory"
set_module_property TOP_LEVEL_HDL_FILE acl_mem2x.v
set_module_property TOP_LEVEL_HDL_MODULE acl_mem2x
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file acl_mem2x.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter LOG2DEPTH INTEGER 14
set_parameter_property LOG2DEPTH DEFAULT_VALUE 14
set_parameter_property LOG2DEPTH DISPLAY_NAME "Log2 of the size of the memory in words"
set_parameter_property LOG2DEPTH TYPE INTEGER
set_parameter_property LOG2DEPTH UNITS None
set_parameter_property LOG2DEPTH ALLOWED_RANGES 0:32
set_parameter_property LOG2DEPTH AFFECTS_GENERATION false
set_parameter_property LOG2DEPTH HDL_PARAMETER true
add_parameter WIDTH INTEGER 32
set_parameter_property WIDTH DEFAULT_VALUE 32
set_parameter_property WIDTH DISPLAY_NAME "Width of each port in bits"
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES 1:16386
set_parameter_property WIDTH AFFECTS_GENERATION false
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter NUMPORTS INTEGER 32
set_parameter_property NUMPORTS DEFAULT_VALUE 4
set_parameter_property NUMPORTS DISPLAY_NAME "Number of ports desired (1-4)"
set_parameter_property NUMPORTS TYPE INTEGER
set_parameter_property NUMPORTS UNITS None
set_parameter_property NUMPORTS ALLOWED_RANGES 1:4
set_parameter_property NUMPORTS AFFECTS_GENERATION false
set_parameter_property NUMPORTS HDL_PARAMETER false
# | 
# +-----------------------------------


# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_reset
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ASSOCIATED_CLOCK clock_reset
set_interface_property clock_reset ENABLED true
add_interface_port clock_reset resetn reset_n Input 1

# +-----------------------------------
# | connection point port1
# | 
add_interface port1 avalon end
set_interface_property port1 addressAlignment DYNAMIC
set_interface_property port1 addressUnits WORDS
set_interface_property port1 associatedClock clock
set_interface_property port1 associatedReset clock_reset
set_interface_property port1 burstOnBurstBoundariesOnly false
set_interface_property port1 explicitAddressSpan 0
set_interface_property port1 holdTime 0
set_interface_property port1 isMemoryDevice true
set_interface_property port1 isNonVolatileStorage true
set_interface_property port1 linewrapBursts false
#set_interface_property port1 maximumPendingReadTransactions 5
set_interface_property port1 printableDevice false
set_interface_property port1 readLatency 4
set_interface_property port1 readWaitTime 1
set_interface_property port1 setupTime 0
set_interface_property port1 timingUnits Cycles
set_interface_property port1 writeWaitTime 0

set_interface_property port1 ENABLED true

add_interface_port port1 avs_port1_writedata writedata Input WIDTH
add_interface_port port1 avs_port1_byteenable byteenable Input WIDTH/8
add_interface_port port1 avs_port1_address address Input LOG2DEPTH
add_interface_port port1 avs_port1_read read Input 1
add_interface_port port1 avs_port1_write write Input 1
add_interface_port port1 avs_port1_readdata readdata Output WIDTH
#add_interface_port port1 avs_port1_readdatavalid readdatavalid Output 1
add_interface_port port1 avs_port1_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point port2
# | 
add_interface port2 avalon end
set_interface_property port2 addressAlignment DYNAMIC
set_interface_property port2 addressUnits WORDS
set_interface_property port2 associatedClock clock
set_interface_property port2 associatedReset clock_reset
set_interface_property port2 burstOnBurstBoundariesOnly false
set_interface_property port2 explicitAddressSpan 0
set_interface_property port2 holdTime 0
set_interface_property port2 isMemoryDevice true
set_interface_property port2 isNonVolatileStorage true
set_interface_property port2 linewrapBursts false
#set_interface_property port2 maximumPendingReadTransactions 5
set_interface_property port2 printableDevice false
set_interface_property port2 readLatency 4
set_interface_property port2 readWaitTime 1
set_interface_property port2 setupTime 0
set_interface_property port2 timingUnits Cycles
set_interface_property port2 writeWaitTime 0

add_interface_port port2 avs_port2_writedata writedata Input WIDTH
add_interface_port port2 avs_port2_byteenable byteenable Input WIDTH/8
add_interface_port port2 avs_port2_address address Input LOG2DEPTH
add_interface_port port2 avs_port2_read read Input 1
add_interface_port port2 avs_port2_write write Input 1
add_interface_port port2 avs_port2_readdata readdata Output WIDTH
#add_interface_port port2 avs_port2_readdatavalid readdatavalid Output 1
add_interface_port port2 avs_port2_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point port3
# | 
add_interface port3 avalon end
set_interface_property port3 addressAlignment DYNAMIC
set_interface_property port3 addressUnits WORDS
set_interface_property port3 associatedClock clock
set_interface_property port3 associatedReset clock_reset
set_interface_property port3 burstOnBurstBoundariesOnly false
set_interface_property port3 explicitAddressSpan 0
set_interface_property port3 holdTime 0
set_interface_property port3 isMemoryDevice true
set_interface_property port3 isNonVolatileStorage true
set_interface_property port3 linewrapBursts false
#set_interface_property port3 maximumPendingReadTransactions 5
set_interface_property port3 printableDevice false
set_interface_property port3 readLatency 4
set_interface_property port3 readWaitTime 1
set_interface_property port3 setupTime 0
set_interface_property port3 timingUnits Cycles
set_interface_property port3 writeWaitTime 0

add_interface_port port3 avs_port3_writedata writedata Input WIDTH
add_interface_port port3 avs_port3_byteenable byteenable Input WIDTH/8
add_interface_port port3 avs_port3_address address Input LOG2DEPTH
add_interface_port port3 avs_port3_read read Input 1
add_interface_port port3 avs_port3_write write Input 1
add_interface_port port3 avs_port3_readdata readdata Output WIDTH
#add_interface_port port3 avs_port3_readdatavalid readdatavalid Output 1
add_interface_port port3 avs_port3_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point port4
# | 
add_interface port4 avalon end
set_interface_property port4 addressAlignment DYNAMIC
set_interface_property port4 addressUnits WORDS
set_interface_property port4 associatedClock clock
set_interface_property port4 associatedReset clock_reset
set_interface_property port4 burstOnBurstBoundariesOnly false
set_interface_property port4 explicitAddressSpan 0
set_interface_property port4 holdTime 0
set_interface_property port4 isMemoryDevice true
set_interface_property port4 isNonVolatileStorage true
set_interface_property port4 linewrapBursts false
#set_interface_property port4 maximumPendingReadTransactions 5
set_interface_property port4 printableDevice false
set_interface_property port4 readLatency 4
set_interface_property port4 readWaitTime 1
set_interface_property port4 setupTime 0
set_interface_property port4 timingUnits Cycles
set_interface_property port4 writeWaitTime 0

add_interface_port port4 avs_port4_writedata writedata Input WIDTH
add_interface_port port4 avs_port4_byteenable byteenable Input WIDTH/8
add_interface_port port4 avs_port4_address address Input LOG2DEPTH
add_interface_port port4 avs_port4_read read Input 1
add_interface_port port4 avs_port4_write write Input 1
add_interface_port port4 avs_port4_readdata readdata Output WIDTH
#add_interface_port port4 avs_port4_readdatavalid readdatavalid Output 1
add_interface_port port4 avs_port4_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clk2x clk Input 1
# | 
# +-----------------------------------

set_module_property elaboration_Callback mem_elaborate

proc mem_elaborate {} {

  if { [ get_parameter_value NUMPORTS ] > 1 } {
    set_interface_property port2 ENABLED true
  } else {
    set_interface_property port2 ENABLED false
  }
  if { [ get_parameter_value NUMPORTS ] > 2 } {
    set_interface_property port3 ENABLED true
  } else {
    set_interface_property port3 ENABLED false
  }
  if { [ get_parameter_value NUMPORTS ] > 3 } {
    set_interface_property port4 ENABLED true
  } else {
    set_interface_property port4 ENABLED false
  }
}
