
-- (C) 1992-2014 Altera Corporation. All rights reserved.                         
-- Your use of Altera Corporation's design tools, logic functions and other       
-- software and tools, and its AMPP partner logic functions, and any output       
-- files any of the foregoing (including device programming or simulation         
-- files), and any associated documentation or information are expressly subject  
-- to the terms and conditions of the Altera Program License Subscription         
-- Agreement, Altera MegaCore Function License Agreement, or other applicable     
-- license agreement, including, without limitation, that your use is for the     
-- sole purpose of programming logic devices manufactured by Altera and sold by   
-- Altera or its authorized distributors.  Please refer to the applicable         
-- agreement for further details.                                                 
    


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
USE ieee.std_logic_arith.all;

--***************************************************
--***                                             ***
--***   FLOATING POINT CORE LIBRARY               ***
--***                                             ***
--***   FP_EXPLUTNEG.VHD                          ***
--***                                             ***
--***   Function: Look Up Table - EXP()           ***
--***                                             ***
--***   Generated by MATLAB Utility               ***
--***                                             ***
--***   18/02/08 ML                               ***
--***                                             ***
--***   (c) 2008 Altera Corporation               ***
--***                                             ***
--***   Change History                            ***
--***                                             ***
--***                                             ***
--***                                             ***
--***                                             ***
--***                                             ***
--***************************************************

ENTITY fp_explutneg IS
PORT (
      address : IN STD_LOGIC_VECTOR (7 DOWNTO 1);
      mantissa : OUT STD_LOGIC_VECTOR (23 DOWNTO 1);
      exponent : OUT STD_LOGIC_VECTOR (8 DOWNTO 1)
     );
END fp_explutneg;

ARCHITECTURE rtl OF fp_explutneg IS

BEGIN

  pca: PROCESS (address)
  BEGIN
    CASE address IS
      WHEN "0000000" =>
            mantissa <= conv_std_logic_vector(0,23);
            exponent <= conv_std_logic_vector(127,8);
      WHEN "0000001" =>
            mantissa <= conv_std_logic_vector(3955378,23);
            exponent <= conv_std_logic_vector(125,8);
      WHEN "0000010" =>
            mantissa <= conv_std_logic_vector(693589,23);
            exponent <= conv_std_logic_vector(124,8);
      WHEN "0000011" =>
            mantissa <= conv_std_logic_vector(4976006,23);
            exponent <= conv_std_logic_vector(122,8);
      WHEN "0000100" =>
            mantissa <= conv_std_logic_vector(1444526,23);
            exponent <= conv_std_logic_vector(121,8);
      WHEN "0000101" =>
            mantissa <= conv_std_logic_vector(6081023,23);
            exponent <= conv_std_logic_vector(119,8);
      WHEN "0000110" =>
            mantissa <= conv_std_logic_vector(2257552,23);
            exponent <= conv_std_logic_vector(118,8);
      WHEN "0000111" =>
            mantissa <= conv_std_logic_vector(7277405,23);
            exponent <= conv_std_logic_vector(116,8);
      WHEN "0001000" =>
            mantissa <= conv_std_logic_vector(3137800,23);
            exponent <= conv_std_logic_vector(115,8);
      WHEN "0001001" =>
            mantissa <= conv_std_logic_vector(92049,23);
            exponent <= conv_std_logic_vector(114,8);
      WHEN "0001010" =>
            mantissa <= conv_std_logic_vector(4090830,23);
            exponent <= conv_std_logic_vector(112,8);
      WHEN "0001011" =>
            mantissa <= conv_std_logic_vector(793249,23);
            exponent <= conv_std_logic_vector(111,8);
      WHEN "0001100" =>
            mantissa <= conv_std_logic_vector(5122658,23);
            exponent <= conv_std_logic_vector(109,8);
      WHEN "0001101" =>
            mantissa <= conv_std_logic_vector(1552426,23);
            exponent <= conv_std_logic_vector(108,8);
      WHEN "0001110" =>
            mantissa <= conv_std_logic_vector(6239800,23);
            exponent <= conv_std_logic_vector(106,8);
      WHEN "0001111" =>
            mantissa <= conv_std_logic_vector(2374373,23);
            exponent <= conv_std_logic_vector(105,8);
      WHEN "0010000" =>
            mantissa <= conv_std_logic_vector(7449310,23);
            exponent <= conv_std_logic_vector(103,8);
      WHEN "0010001" =>
            mantissa <= conv_std_logic_vector(3264281,23);
            exponent <= conv_std_logic_vector(102,8);
      WHEN "0010010" =>
            mantissa <= conv_std_logic_vector(185108,23);
            exponent <= conv_std_logic_vector(101,8);
      WHEN "0010011" =>
            mantissa <= conv_std_logic_vector(4227768,23);
            exponent <= conv_std_logic_vector(99,8);
      WHEN "0010100" =>
            mantissa <= conv_std_logic_vector(894003,23);
            exponent <= conv_std_logic_vector(98,8);
      WHEN "0010101" =>
            mantissa <= conv_std_logic_vector(5270919,23);
            exponent <= conv_std_logic_vector(96,8);
      WHEN "0010110" =>
            mantissa <= conv_std_logic_vector(1661510,23);
            exponent <= conv_std_logic_vector(95,8);
      WHEN "0010111" =>
            mantissa <= conv_std_logic_vector(6400319,23);
            exponent <= conv_std_logic_vector(93,8);
      WHEN "0011000" =>
            mantissa <= conv_std_logic_vector(2492476,23);
            exponent <= conv_std_logic_vector(92,8);
      WHEN "0011001" =>
            mantissa <= conv_std_logic_vector(7623101,23);
            exponent <= conv_std_logic_vector(90,8);
      WHEN "0011010" =>
            mantissa <= conv_std_logic_vector(3392149,23);
            exponent <= conv_std_logic_vector(89,8);
      WHEN "0011011" =>
            mantissa <= conv_std_logic_vector(279189,23);
            exponent <= conv_std_logic_vector(88,8);
      WHEN "0011100" =>
            mantissa <= conv_std_logic_vector(4366209,23);
            exponent <= conv_std_logic_vector(86,8);
      WHEN "0011101" =>
            mantissa <= conv_std_logic_vector(995862,23);
            exponent <= conv_std_logic_vector(85,8);
      WHEN "0011110" =>
            mantissa <= conv_std_logic_vector(5420806,23);
            exponent <= conv_std_logic_vector(83,8);
      WHEN "0011111" =>
            mantissa <= conv_std_logic_vector(1771791,23);
            exponent <= conv_std_logic_vector(82,8);
      WHEN "0100000" =>
            mantissa <= conv_std_logic_vector(6562600,23);
            exponent <= conv_std_logic_vector(80,8);
      WHEN "0100001" =>
            mantissa <= conv_std_logic_vector(2611876,23);
            exponent <= conv_std_logic_vector(79,8);
      WHEN "0100010" =>
            mantissa <= conv_std_logic_vector(7798799,23);
            exponent <= conv_std_logic_vector(77,8);
      WHEN "0100011" =>
            mantissa <= conv_std_logic_vector(3521421,23);
            exponent <= conv_std_logic_vector(76,8);
      WHEN "0100100" =>
            mantissa <= conv_std_logic_vector(374301,23);
            exponent <= conv_std_logic_vector(75,8);
      WHEN "0100101" =>
            mantissa <= conv_std_logic_vector(4506169,23);
            exponent <= conv_std_logic_vector(73,8);
      WHEN "0100110" =>
            mantissa <= conv_std_logic_vector(1098839,23);
            exponent <= conv_std_logic_vector(72,8);
      WHEN "0100111" =>
            mantissa <= conv_std_logic_vector(5572338,23);
            exponent <= conv_std_logic_vector(70,8);
      WHEN "0101000" =>
            mantissa <= conv_std_logic_vector(1883282,23);
            exponent <= conv_std_logic_vector(69,8);
      WHEN "0101001" =>
            mantissa <= conv_std_logic_vector(6726661,23);
            exponent <= conv_std_logic_vector(67,8);
      WHEN "0101010" =>
            mantissa <= conv_std_logic_vector(2732585,23);
            exponent <= conv_std_logic_vector(66,8);
      WHEN "0101011" =>
            mantissa <= conv_std_logic_vector(7976426,23);
            exponent <= conv_std_logic_vector(64,8);
      WHEN "0101100" =>
            mantissa <= conv_std_logic_vector(3652111,23);
            exponent <= conv_std_logic_vector(63,8);
      WHEN "0101101" =>
            mantissa <= conv_std_logic_vector(470458,23);
            exponent <= conv_std_logic_vector(62,8);
      WHEN "0101110" =>
            mantissa <= conv_std_logic_vector(4647665,23);
            exponent <= conv_std_logic_vector(60,8);
      WHEN "0101111" =>
            mantissa <= conv_std_logic_vector(1202946,23);
            exponent <= conv_std_logic_vector(59,8);
      WHEN "0110000" =>
            mantissa <= conv_std_logic_vector(5725533,23);
            exponent <= conv_std_logic_vector(57,8);
      WHEN "0110001" =>
            mantissa <= conv_std_logic_vector(1995997,23);
            exponent <= conv_std_logic_vector(56,8);
      WHEN "0110010" =>
            mantissa <= conv_std_logic_vector(6892523,23);
            exponent <= conv_std_logic_vector(54,8);
      WHEN "0110011" =>
            mantissa <= conv_std_logic_vector(2854620,23);
            exponent <= conv_std_logic_vector(53,8);
      WHEN "0110100" =>
            mantissa <= conv_std_logic_vector(8156001,23);
            exponent <= conv_std_logic_vector(51,8);
      WHEN "0110101" =>
            mantissa <= conv_std_logic_vector(3784235,23);
            exponent <= conv_std_logic_vector(50,8);
      WHEN "0110110" =>
            mantissa <= conv_std_logic_vector(567669,23);
            exponent <= conv_std_logic_vector(49,8);
      WHEN "0110111" =>
            mantissa <= conv_std_logic_vector(4790713,23);
            exponent <= conv_std_logic_vector(47,8);
      WHEN "0111000" =>
            mantissa <= conv_std_logic_vector(1308195,23);
            exponent <= conv_std_logic_vector(46,8);
      WHEN "0111001" =>
            mantissa <= conv_std_logic_vector(5880410,23);
            exponent <= conv_std_logic_vector(44,8);
      WHEN "0111010" =>
            mantissa <= conv_std_logic_vector(2109948,23);
            exponent <= conv_std_logic_vector(43,8);
      WHEN "0111011" =>
            mantissa <= conv_std_logic_vector(7060204,23);
            exponent <= conv_std_logic_vector(41,8);
      WHEN "0111100" =>
            mantissa <= conv_std_logic_vector(2977993,23);
            exponent <= conv_std_logic_vector(40,8);
      WHEN "0111101" =>
            mantissa <= conv_std_logic_vector(8337547,23);
            exponent <= conv_std_logic_vector(38,8);
      WHEN "0111110" =>
            mantissa <= conv_std_logic_vector(3917809,23);
            exponent <= conv_std_logic_vector(37,8);
      WHEN "0111111" =>
            mantissa <= conv_std_logic_vector(665948,23);
            exponent <= conv_std_logic_vector(36,8);
      WHEN "1000000" =>
            mantissa <= conv_std_logic_vector(4935332,23);
            exponent <= conv_std_logic_vector(34,8);
      WHEN "1000001" =>
            mantissa <= conv_std_logic_vector(1414599,23);
            exponent <= conv_std_logic_vector(33,8);
      WHEN "1000010" =>
            mantissa <= conv_std_logic_vector(6036985,23);
            exponent <= conv_std_logic_vector(31,8);
      WHEN "1000011" =>
            mantissa <= conv_std_logic_vector(2225150,23);
            exponent <= conv_std_logic_vector(30,8);
      WHEN "1000100" =>
            mantissa <= conv_std_logic_vector(7229726,23);
            exponent <= conv_std_logic_vector(28,8);
      WHEN "1000101" =>
            mantissa <= conv_std_logic_vector(3102720,23);
            exponent <= conv_std_logic_vector(27,8);
      WHEN "1000110" =>
            mantissa <= conv_std_logic_vector(66239,23);
            exponent <= conv_std_logic_vector(26,8);
      WHEN "1000111" =>
            mantissa <= conv_std_logic_vector(4052849,23);
            exponent <= conv_std_logic_vector(24,8);
      WHEN "1001000" =>
            mantissa <= conv_std_logic_vector(765304,23);
            exponent <= conv_std_logic_vector(23,8);
      WHEN "1001001" =>
            mantissa <= conv_std_logic_vector(5081537,23);
            exponent <= conv_std_logic_vector(21,8);
      WHEN "1001010" =>
            mantissa <= conv_std_logic_vector(1522171,23);
            exponent <= conv_std_logic_vector(20,8);
      WHEN "1001011" =>
            mantissa <= conv_std_logic_vector(6195279,23);
            exponent <= conv_std_logic_vector(18,8);
      WHEN "1001100" =>
            mantissa <= conv_std_logic_vector(2341616,23);
            exponent <= conv_std_logic_vector(17,8);
      WHEN "1001101" =>
            mantissa <= conv_std_logic_vector(7401108,23);
            exponent <= conv_std_logic_vector(15,8);
      WHEN "1001110" =>
            mantissa <= conv_std_logic_vector(3228816,23);
            exponent <= conv_std_logic_vector(14,8);
      WHEN "1001111" =>
            mantissa <= conv_std_logic_vector(159015,23);
            exponent <= conv_std_logic_vector(13,8);
      WHEN "1010000" =>
            mantissa <= conv_std_logic_vector(4189370,23);
            exponent <= conv_std_logic_vector(11,8);
      WHEN "1010001" =>
            mantissa <= conv_std_logic_vector(865751,23);
            exponent <= conv_std_logic_vector(10,8);
      WHEN "1010010" =>
            mantissa <= conv_std_logic_vector(5229346,23);
            exponent <= conv_std_logic_vector(8,8);
      WHEN "1010011" =>
            mantissa <= conv_std_logic_vector(1630923,23);
            exponent <= conv_std_logic_vector(7,8);
      WHEN "1010100" =>
            mantissa <= conv_std_logic_vector(6355309,23);
            exponent <= conv_std_logic_vector(5,8);
      WHEN "1010101" =>
            mantissa <= conv_std_logic_vector(2459360,23);
            exponent <= conv_std_logic_vector(4,8);
      WHEN "1010110" =>
            mantissa <= conv_std_logic_vector(7574370,23);
            exponent <= conv_std_logic_vector(2,8);
      WHEN "1010111" =>
            mantissa <= conv_std_logic_vector(3356295,23);
            exponent <= conv_std_logic_vector(1,8);
      WHEN "1011000" =>
            mantissa <= conv_std_logic_vector(252809,23);
            exponent <= conv_std_logic_vector(0,8);
      WHEN "1011001" =>
            mantissa <= conv_std_logic_vector(4327390,23);
            exponent <= conv_std_logic_vector(-2,8);
      WHEN others =>
           mantissa <= conv_std_logic_vector(0,23);
           exponent <= conv_std_logic_vector(0,8);
    END CASE;
  END PROCESS;

END rtl;
